language: java
install:
- mvn install
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: tNhauadrIdGkptcO58e2aoh9pMD3NF9G2gV6OzIFCdOCPbs3GyJPwZmkdLkUsPs0uRRTUQQFkwz1xvusC9o2P53242f0lQPHy6uQgz3JmK9VZd6CCDwesJSaM/C3UBUuWF4oPw8PNq0vBtNWjxELgqK+4YyB9Pm+l0fulTfB3dc3hpo77enfcx8+Js1T5OysuhXX1XR0+bnBirMNzjnx/VFz+Kf51dda/LLN0Rqo+nmbRALDRnxsfKNVtD9RbkSqM+aAG6/6qd1XzrdJL3uWzZLuOhbC7ZzQdBgX+vFAOz93RTMTymxKPexF5n598lPPNUvSuugGLSB1vsnnfQpP6ndQx5UEGnMgXO6Cvuuc3R1O7TpXznH4t3qEZd2uzIkxNjYSkTOZ5G6AHAjHPcneOS5+MfsF+XANxgACM0IGaEfxaQj+M2RsWn9Ch/OlH6dhpNd72MxTXZhscsBCYurKCIOJfjD9deJ6JRWqPiwQxrjTl/jaumRP/xEV5HEwNND0cB0hSAITvKPcb4hqSCTIBhNnS6iF9yRkkCvwjiWWGGN9qB9Mkln7rkOH7dVRyrI3iDEeJ0FjKW9pNtdddgpJ0bfC5s4hpEQosc7eyOuJIvK3RsePaHti6dRXmjTpfvamu6Rb1WmJRMxg1QptuUu/3YnF3gh1qrzY6zJxv5repJc=
  app: charon-3130
  on:
    repo: CSCI3130-Amadeus/charon
